- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: v1.2.3
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: flake8
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.7
